(async () => {
  const frame = document.getElementById('active-frame');
  const w = frame.contentWindow; const d = w.document; const p = w.__FOA_POWERMAP__;
  const assert = (ok, message) => { if (!ok) throw new Error(message); };
  const choose = (id, value) => { if (id === 'view') { d.getElementById(`view-${value}`).click(); return; } const el = d.getElementById(id); el.value = value; el.dispatchEvent(new w.Event('change')); };
  choose('view', 'spatial');
  const view = p.view; assert(view?.active, d.getElementById('detail').textContent);
  const pixels = () => {
    view.render(); const gl = view.gpu.getContext();
    const bytes = new Uint8Array(gl.drawingBufferWidth * gl.drawingBufferHeight * 4);
    gl.readPixels(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight, gl.RGBA, gl.UNSIGNED_BYTE, bytes);
    let lit = 0; for (let i = 0; i < bytes.length; i += 4) if (bytes[i] + bytes[i + 1] + bytes[i + 2] > 15) lit++;
    return lit;
  };
  const enabled = d.getElementById('enabled'); enabled.checked = false; enabled.dispatchEvent(new w.Event('change'));
  choose('projection', '180'); view.reset(); const front = pixels();
  view.orient(Math.PI, 0); const rear180 = pixels();
  choose('projection', '360'); const rear360 = pixels();
  assert(front > 1000 && rear180 === 0 && rear360 > 1000, `ERP pixels: ${front}/${rear180}/${rear360}`);
  choose('projection', '180'); view.reset();
  const host = d.getElementById('spatial');
  host.dispatchEvent(new w.KeyboardEvent('keydown', { key: 'ArrowLeft', bubbles: true }));
  assert(view.yaw > 0, 'Keyboard look failed');
  host.dispatchEvent(new w.WheelEvent('wheel', { deltaY: -200, cancelable: true }));
  assert(view.camera.fov < 72, 'Wheel zoom failed');
  view.orient(0, 9); assert(view.pitch < Math.PI / 2, 'Pitch not clamped');
  d.getElementById('reset-view').click(); assert(view.yaw === 0 && view.pitch === 0 && view.camera.fov === 72, 'Reset failed');
  const render = async yaw => {
    view.orient(yaw, 0);
    const context = new w.OfflineAudioContext(2, 4096, 48000);
    const renderer = w.Omnitone.createFOARenderer(context, { channelMap: [0, 1, 2, 3] });
    await renderer.initialize(); renderer.setRotationMatrixFromCamera(p.monitor.orientation);
    const buffer = context.createBuffer(4, 4096, 48000);
    buffer.getChannelData(0)[0] = .25; buffer.getChannelData(3)[0] = .25;
    const source = context.createBufferSource(); source.buffer = buffer;
    source.connect(renderer.input); renderer.output.connect(context.destination); source.start();
    const audio = await context.startRendering();
    return [0, 1].map(ch => audio.getChannelData(ch).reduce((sum, v) => sum + v * v, 0));
  };
  const lookLeft = await render(Math.PI / 2); const lookRight = await render(-Math.PI / 2);
  assert(lookLeft[1] > lookLeft[0] * 2 && lookRight[0] > lookRight[1] * 2, 'Camera-relative ears reversed');
  choose('view', 'flat');
  assert(p.monitor.orientation.elements.every((x, i) => Math.abs(x - (i % 5 === 0 ? 1 : 0)) < 1e-6), 'Flat audio not forward');
  choose('view', 'spatial'); view.reset();
  const map = d.getElementById('overlay').getContext('2d');
  const savedMap = map.getImageData(0, 0, 140, 70);
  map.clearRect(0, 0, 140, 70); map.fillStyle = 'white'; map.fillRect(51, 22, 4, 4);
  view.background.visible = false; view.orient(Math.PI / 4, Math.PI / 6); view.mapChanged(); view.render();
  const gl = view.gpu.getContext(); const center = new Uint8Array(4);
  gl.readPixels(Math.floor(gl.drawingBufferWidth / 2), Math.floor(gl.drawingBufferHeight / 2), 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, center);
  map.putImageData(savedMap, 0, 0); view.background.visible = true; view.reset(); view.mapChanged();
  assert(center[0] > 100, 'Map direction does not match camera');
  enabled.checked = true; enabled.dispatchEvent(new w.Event('change'));
  const oldWidth = frame.style.width; frame.style.width = '390px';
  await new Promise(resolve => setTimeout(resolve, 200));
  assert(d.documentElement.scrollWidth <= w.innerWidth && pixels() > 100, 'Narrow view blank or overflowing');
  w.__FOA_VIEW_RESTORE__ = () => { frame.style.width = oldWidth; };
  return { front, rear180, rear360, lookLeft, lookRight, state: p.getState() };
})()
